// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: demo

#include "ui.h"
#include "driver/gpio.h"

void Lamp_on(lv_event_t * e)
{
	// Your code here
	printf("open led\n");
	gpio_set_level(19, 1);
}

void Lamp_off(lv_event_t * e)
{
	// Your code here
	printf("close led\n");
	gpio_set_level(19, 0);
}
