

idf_component_register(
                    SRCS 
                    "CrowPanel_ESP32_7.0.cpp"
                    INCLUDE_DIRS
                    "."
                    "../components/arduino-esp32"                 
                    "../components/LovyanGFX-master"   
                    )
