// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Desktop_Effect

#ifndef _DESKTOP_EFFECT_UI_H
#define _DESKTOP_EFFECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Title1;
extern lv_obj_t * ui_LocalImage;
extern lv_obj_t * ui_DateImage;
extern lv_obj_t * ui_TimeImage;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_LocalLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Title2;
extern lv_obj_t * ui_WeatherImage;
extern lv_obj_t * ui_WeatherLabel;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_TempImage;
extern lv_obj_t * ui_HumiImage;
extern lv_obj_t * ui_WindImage;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_HumiLabel;
extern lv_obj_t * ui_WindLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Title3;
extern lv_obj_t * ui_MusicImage;
void ui_event_PreviousButton(lv_event_t * e);
extern lv_obj_t * ui_PreviousButton;
void ui_event_NextButton(lv_event_t * e);
extern lv_obj_t * ui_NextButton;
void ui_event_PlayOrPauseButton(lv_event_t * e);
extern lv_obj_t * ui_PlayOrPauseButton;
extern lv_obj_t * ui_PlayOrPauseLabel;
extern lv_obj_t * ui_MusicStatusLabel;
extern lv_obj_t * ui_SongNameLabel;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Title4;
extern lv_obj_t * ui_HourDropdown;
extern lv_obj_t * ui_MinDropdown;
void ui_event_ClockSwitch(lv_event_t * e);
extern lv_obj_t * ui_ClockSwitch;
extern lv_obj_t * ui_HourAlarm;
extern lv_obj_t * ui_MinAlarm;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
void ui_event_StopButton(lv_event_t * e);
extern lv_obj_t * ui_StopButton;
extern lv_obj_t * ui_StopLabel;
void ui_event_StartButton(lv_event_t * e);
extern lv_obj_t * ui_StartButton;
extern lv_obj_t * ui_StartLabel;
void ui_event_ClearButton(lv_event_t * e);
extern lv_obj_t * ui_ClearButton;
extern lv_obj_t * ui_ClearLabel;
extern lv_obj_t * ui_TimerLabel;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Title6;
extern lv_obj_t * ui_OnImage;
extern lv_obj_t * ui_OffImage;
void ui_event_OnButton(lv_event_t * e);
extern lv_obj_t * ui_OnButton;
extern lv_obj_t * ui_OnLabel;
void ui_event_OffButton(lv_event_t * e);
extern lv_obj_t * ui_OffButton;
extern lv_obj_t * ui_OffLabel;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1241096081);    // assets/背景01.png
LV_IMG_DECLARE(ui_img_35292644);    // assets/定位2.png
LV_IMG_DECLARE(ui_img_2138131786);    // assets/日历.png
LV_IMG_DECLARE(ui_img_608756609);    // assets/闹钟.png
LV_IMG_DECLARE(ui_img_800x400_png);    // assets/800x400.png
LV_IMG_DECLARE(ui_img_sunny_png);    // assets/sunny.png
LV_IMG_DECLARE(ui_img_843332074);    // assets/温度.png
LV_IMG_DECLARE(ui_img_545021016);    // assets/湿度.png
LV_IMG_DECLARE(ui_img_2008377658);    // assets/风力.png
LV_IMG_DECLARE(ui_img_1241089683);    // assets/背景03.png
LV_IMG_DECLARE(ui_img_1763876406);    // assets/音乐盒.png
LV_IMG_DECLARE(ui_img_1136831542);    // assets/上一首1.png
LV_IMG_DECLARE(ui_img_1663666363);    // assets/下一首1.png
LV_IMG_DECLARE(ui_img_1241099404);    // assets/背景04.png
LV_IMG_DECLARE(ui_img_800x480_png);    // assets/800x480.png
LV_IMG_DECLARE(ui_img_1241093006);    // assets/背景06.png
LV_IMG_DECLARE(ui_img_1098477250);    // assets/已开灯.png
LV_IMG_DECLARE(ui_img_557842394);    // assets/未开灯.png

// FONTS
LV_FONT_DECLARE(ui_font_BodoniFont36);
LV_FONT_DECLARE(ui_font_BodoniFont46);
LV_FONT_DECLARE(ui_font_BodoniModaFont36);
LV_FONT_DECLARE(ui_font_BodoniModaFont46);
LV_FONT_DECLARE(ui_font_BodoniFont64);
LV_FONT_DECLARE(ui_font_BodoniFont54);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
