// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: advance-big

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_tempLabel1 = NULL;
lv_obj_t * ui_HumiLabel2 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabel1, -41);
    lv_obj_set_y(ui_tempLabel1, -104);
    lv_obj_set_align(ui_tempLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel1, "25");
    lv_obj_set_style_text_font(ui_tempLabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiLabel2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HumiLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiLabel2, -42);
    lv_obj_set_y(ui_HumiLabel2, 43);
    lv_obj_set_align(ui_HumiLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumiLabel2, "60");
    lv_obj_set_style_text_font(ui_HumiLabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_delete(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_tempLabel1 = NULL;
    ui_HumiLabel2 = NULL;

}
