// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: advance-3-big

#include "ui.h"
#include "driver/gpio.h"

#define LAMP_GPIO GPIO_NUM_19

void Lamp_on(lv_event_t * e)
{
	gpio_set_level(LAMP_GPIO, 1);
}

void Lamp_off(lv_event_t * e)
{
	gpio_set_level(LAMP_GPIO, 0);
}
