// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: advance-3-big

#include "ui.h"
#include <Arduino.h>

void Lamp_on(lv_event_t * e)
{
	digitalWrite(19, HIGH);
}

void Lamp_off(lv_event_t * e)
{
	digitalWrite(19, LOW);
}
