// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: advance-3-big

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Lamp_on(lv_event_t * e);
void Lamp_off(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
