// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Desktop_Effect

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Title3 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_Title3, &ui_img_1241089683);
    lv_obj_set_width(ui_Title3, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Title3, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Title3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Title3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Title3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MusicImage = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_MusicImage, &ui_img_1763876406);
    lv_obj_set_width(ui_MusicImage, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_MusicImage, LV_SIZE_CONTENT);    /// 220
    lv_obj_set_x(ui_MusicImage, 0);
    lv_obj_set_y(ui_MusicImage, -48);
    lv_obj_set_align(ui_MusicImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MusicImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MusicImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PreviousButton = lv_imagebutton_create(ui_Screen3);
    lv_imagebutton_set_src(ui_PreviousButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1136831542, NULL);
    lv_imagebutton_set_src(ui_PreviousButton, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1136831542, NULL);
    lv_obj_set_width(ui_PreviousButton, lv_pct(11));
    lv_obj_set_height(ui_PreviousButton, lv_pct(15));
    lv_obj_set_x(ui_PreviousButton, -260);
    lv_obj_set_y(ui_PreviousButton, 150);
    lv_obj_set_align(ui_PreviousButton, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_PreviousButton, lv_color_hex(0xE6EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PreviousButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PreviousButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PreviousButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PreviousButton, lv_color_hex(0xE6EEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PreviousButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PreviousButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PreviousButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PreviousButton, lv_color_hex(0x009DEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PreviousButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PreviousButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PreviousButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_PreviousButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_PreviousButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextButton = lv_imagebutton_create(ui_Screen3);
    lv_imagebutton_set_src(ui_NextButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_1663666363, NULL);
    lv_imagebutton_set_src(ui_NextButton, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_1663666363, NULL);
    lv_obj_set_width(ui_NextButton, lv_pct(11));
    lv_obj_set_height(ui_NextButton, lv_pct(15));
    lv_obj_set_x(ui_NextButton, 220);
    lv_obj_set_y(ui_NextButton, 150);
    lv_obj_set_align(ui_NextButton, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_NextButton, lv_color_hex(0xE6ECFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NextButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NextButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_NextButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_NextButton, lv_color_hex(0xF6FAFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_NextButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_NextButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_NextButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NextButton, lv_color_hex(0x009DEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NextButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_NextButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_NextButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_NextButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_NextButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlayOrPauseButton = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_PlayOrPauseButton, 150);
    lv_obj_set_height(ui_PlayOrPauseButton, 150);
    lv_obj_set_x(ui_PlayOrPauseButton, -20);
    lv_obj_set_y(ui_PlayOrPauseButton, 150);
    lv_obj_set_align(ui_PlayOrPauseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlayOrPauseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PlayOrPauseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PlayOrPauseButton, lv_color_hex(0xEEF2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlayOrPauseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PlayOrPauseButton, lv_color_hex(0x39B6EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PlayOrPauseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PlayOrPauseButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PlayOrPauseButton, lv_color_hex(0x009DEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PlayOrPauseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PlayOrPauseButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PlayOrPauseButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PlayOrPauseButton, lv_color_hex(0x009DEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PlayOrPauseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PlayOrPauseButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PlayOrPauseButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_PlayOrPauseButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_PlayOrPauseButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlayOrPauseLabel = lv_label_create(ui_PlayOrPauseButton);
    lv_obj_set_width(ui_PlayOrPauseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlayOrPauseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PlayOrPauseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlayOrPauseLabel, "Play");
    lv_obj_set_style_text_color(ui_PlayOrPauseLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlayOrPauseLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlayOrPauseLabel, &ui_font_BodoniFont46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicStatusLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_MusicStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicStatusLabel, 293);
    lv_obj_set_y(ui_MusicStatusLabel, -204);
    lv_obj_set_align(ui_MusicStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicStatusLabel, "PAUSING");
    lv_obj_set_style_text_color(ui_MusicStatusLabel, lv_color_hex(0xFF1000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MusicStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MusicStatusLabel, &ui_font_BodoniModaFont36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MusicStatusLabel, lv_color_hex(0x00DDFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MusicStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MusicStatusLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MusicStatusLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MusicStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_MusicStatusLabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_MusicStatusLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_MusicStatusLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_MusicStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_MusicStatusLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_MusicStatusLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_MusicStatusLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_MusicStatusLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SongNameLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_SongNameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SongNameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SongNameLabel, 219);
    lv_obj_set_y(ui_SongNameLabel, 20);
    lv_obj_set_align(ui_SongNameLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SongNameLabel, "------");
    lv_obj_set_style_text_letter_space(ui_SongNameLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SongNameLabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SongNameLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 210);
    lv_obj_set_y(ui_Label7, -30);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Song name:");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_BodoniModaFont36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PreviousButton, ui_event_PreviousButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextButton, ui_event_NextButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlayOrPauseButton, ui_event_PlayOrPauseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
